name: CD

on:
  # Use semantic-release to publish the updated package.json to master branch with a new release and tag
  # deploy-gh-pages is responsible to build production version and publish it to gh-pages branch
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Coverage
        # Could be replaced with coverage-all if you want to ensure new files are tested as well
        run: |
          npm run coverage
          npm run coverage:report
        env:
          NODE_ENV: test
      - name: E2E-tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
        env:
          NODE_ENV: test
      # Will update the package.json file with semantic-release and push it to master with a new tag
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: 44210433+github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: 44210433+github-actions@users.noreply.github.com
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: coverage
