name: CI

on:
  # CD workflow is responsible for building and release on push to master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Coverage
        # Could be replaced with coverage-all if you want to ensure new files are tested as well
        run: |
          npm run coverage
          npm run coverage:report
        env:
          NODE_ENV: test
      - name: E2E-tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
        env:
          NODE_ENV: test
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: coverage
